[profile.default]
solc-version = "0.8.17"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@seaport/=lib/seaport/contracts/',
    'seaport-types/=lib/seaport/lib/seaport-types/',
    'solady/=lib/seaport/lib/solady/src/',
    'murky/=lib/seaport/lib/murky/src/',
    '@openzeppelin/contracts=lib/seaport/lib/openzeppelin-contracts/contracts',
    'seaport-core/=lib/seaport/lib/seaport-core/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
